### ISSUE TITLE
Bugs v3.1

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/Axie_Manager_Bot#170]
400 Bad Request (error code: 50006): Cannot send an empty message
Traceback (most recent call last):
  File "/home/pi/Axie_Manager_Bot/src/cogs/loops/axie_alert.py", line 367, in old_listings
    build,
  File "/home/pi/Axie_Manager_Bot/src/cogs/loops/axie_alert.py", line 218, in send_alert
    await channel.send(mentions)
  File "/home/pi/venv/lib/python3.7/site-packages/discord/abc.py", line 1067, in send
    message_reference=reference)
  File "/home/pi/venv/lib/python3.7/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message

**Comment by StephanAkkerman** [comment]
Error at new_listings
'DataFrame' object has no attribute 'story_id'
Traceback (most recent call last):
  File "/home/pi/Axie_Manager_Bot/src/cogs/loops/axie_alert.py", line 287, in new_listings
    search, build["R1 deviation"], build["R2 deviation"]
  File "/home/pi/Axie_Manager_Bot/src/alerts/genes.py", line 45, in get_genes
    ~genes.story_id.isin(genes[genes.stage == 1]["story_id"].tolist())
  File "/home/pi/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'story_id'

**Comment by StephanAkkerman** [comment]
Send scholar message if they use !qr in private message

**Comment by StephanAkkerman** [comment]
!issue should skip labels without emojis
