### ISSUE TITLE
New listing error

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/Axie_Manager_Bot#77]
Error at new_listings
'DataFrame' object has no attribute 'story_id'
Traceback (most recent call last):
  File "/home/pi/src/cogs/after/alert.py", line 223, in new_listings
    search, build["R1 deviation"], build["R2 deviation"]
  File "/home/pi/src/alerts/genes.py", line 39, in get_genes
    genes = genes.loc[~genes.story_id.isin(genes[genes.stage == 1]["story_id"].tolist())]
  File "/home/pi/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'story_id'

**Comment by StephanAkkerman** [comment]
Added error handling for this to genes.py
